### PR TITLE
Add theme parameter

### PR DESCRIPTION
**Pull request by EmielH**
First of all, thanks for this useful library!

This adds Tippy's theme parameter, so you can specify your own themes. See the [Tippy documentation on themes](https://atomiks.github.io/tippyjs/v6/themes/).

### CODE REVIEW

**Comment by Kapsonfire** [comment]
I've never felt this is needed because styling the svelte compoents itsself felt superior.. anyway this doesnt hurt anyone - so merged. thanks for contributing

**Comment by Kapsonfire** [comment]
Released in 1.1.3

**Comment by EmielH** [comment]
Thanks! I needed a way to style the Tippy box itself in some cases, but not always - give it a different background colour and round the corners a bit more. Afaik this isn't possible when styling the Svelte component that goes inside the popup.

Just out of curiosity, how would you have solved that by styling the Svelte component?

**Comment by Kapsonfire** [comment]
This lib i created for my mobile game (currently in development). I decided to remove the complete Tippy Styling thing and made it myself. Resulting in this: 
image

**Comment by EmielH** [comment]
Looks good! 👍

**Pull request merged**
